//
//  ViewController.m
//  tangotyou3
//
//  Created by Link Kato on 2015/02/03.
//  Copyright (c) 2015年 ___FULLUSERNAME___. All rights reserved.
//

#import "ViewController.h"

@interface ViewController ()

@end

@implementation ViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
	// Do any additional setup after loading the view, typically from a nib.



table.delegate=self;
table.dataSource=self;

nameArray =[[NSMutableArray alloc] initWithObjects:
           
             @"about",
            @"after",
            @"afternoon",
            @"again",
            @"ago",
            @"all",
            @"around",
            @"almost",
            @"also",
            @"am",
            @"America",
            @"and",
            @"animal",
            @"ant",
             @"any",
             @"April",
             @"apron",
            @"are",
             @"area",
             @"all around",
             @"as",
             @"at",
             @"August",
             @"Australia",
            
           
           
            @"back",
             @"bag",
             @"ball",
             @"bar",
             @"baseball",
             @"basketball",
             @"beautiful",
             @"bed",
             @"before",
             @"behind",
             @"between",
             @"big",
             @"bike",
             @"bird",
             @"birthday",
             @"black",
             @"blanket",
             @"blue",
             @"boat",
             @"book",
             @"border",
             @"Boston",
             @"box",
             @"boy",
             @"breakfast",
             @"bridge",
             @"brother",
             @"bus",
             @"busy",
             @"but",
             @"by",
             @"bye",
            
            
            
           
            
            
            @"cable car",
            @"cafeteria",
            @"call",
            @"camera",
            @"camp",
            @"can",
            @"Canada",
            @"cannot",
            @"cap",
            @"car",
            @"care",
            @"take care of~",
            @"careful",
            @"cat",
            @"CD",
            @"chair",
            @"change",
            @"charm",
            @"cheer",
            @"child",
            @"children",
            @"China",
            @"Chinatown",
            @"Chinese",
            @"city",
            @"class",
            @"classroom",
            @"close",
            @"cloud",
            @"cloudy",
            @"cold",
            @"color",
            @"come",
            @"Cook",
            @"cook",
            @"cookie",
            @"country",
            @"Of course",
            @"crowded",
            @"culture",
            @"cup",
            
            
            
            
            
            @"date",
            @"day",
            @"dear",
            @"December",
            @"desk",
            @"different",
            @"difficult",
            @"dinner",
            @"do",
            @"dog",
            @"door",
            @"down",
            @"dream",
            @"drive",
            
            
            
            
            @"each",
            @"early",
            @"earth",
            @"easiry",
            @"easy",
            @"eat",
            @"egg",
            @"eight",
            @"eighteen",
            @"eighth",
            @"eighty",
            @"eleven",
            @"eleventh",
            @"English",
            @"enjoy",
            @"evening",
            @"every",
            @"everyone",
            @"excuse",
            
            
            
            
            
            
            @"fall",
            @"family",
            @"famous",
            @"fan",
            @"father",
            @"favorite",
            @"February",
            @"festival",
            @"fifteen",
            @"fifteenth",
            @"fifth",
            @"fifty",
            @"first",
            @"fish",
            @"five",
            @"flute",
            @"food",
            @"football",
            @"for",
            @"foreign",
            @"fortune cookie",
            @"forty",
            @"four",
            @"fourteen",
            @"fourteenth",
            @"fourth",
            @"free",
            @"Friday",
            @"friend",
            @"from",
            
            
            
            
            
            @"game",
            @"get",
            @"girl",
            @"go",
            @"golden",
            @"goldfish scooping",
            @"good",
            @"goodbye",
            @"grandchild",
            @"grandfather",
            @"grandma",
            @"grandmother",
            @"great",
            @"green",
            @"guess",
            @"guitar",
            @"gym",
            
            
            
            
            @"had",
            @"hair",
            @"happy",
            @"hard",
            @"have",
            @"hat",
            @"he",
            @"head",
            @"headache",
            @"hello",
            @"help",
            @"her",
            @"here",
            @"hers",
            @"hi",
            @"high",
            @"hill",
            @"him",
            @"his",
            @"home",
            @"homework",
            @"horizon",
            @"hospital",
            @"hot",
            @"hour",
            @"house",
            @"huh",
            @"hundred",
            @"hurry",
            
            
            
            
            
            @"ice",
            @"in",
            @"ink",
            @"interesting",
            @"is",
            
            
            
            @"jacket",
            @"jam",
            @"January",
            @"Japan",
            @"japanese",
            @"Japantown",
            @"job",
            @"journalist",
            @"juice",
            @"July",
            @"June",
            @"junior",
            @"just",
            
            
            
            
             @"kid",
            @"kitchen",
            @"know",
            @"koala",
            
            
            
           
           
           
            
           
            @"lake",
            @"language",
            @"last",
            @"late",
            @"leave",
            @"left",
            @"light",
            @"like",
            @"like",
            @"lion",
            @"listen",
            @"live",
            @"London",
            @"long",
            @"look",
            @"lot",
            @"love",
            @"lunch",
            
            
            
            
           
           
            
            
             @"make",
            @"man",
            @"many",
            @"March",
            @"market",
            @"math",
            @"May",
            @"maybe",
            @"me",
            @"meet",
            @"member",
            @"Mexican",
            @"milk",
            @"mine",
            @"minute",
            @"mirror",
            @"miss",
            @"Monday",
            @"month",
            @"moon",
            @"morning",
            @"mother",
            @"much",
            @"music",
            @"my",
            
            
            
            
            
            @"name",
            @"near",
            @"net",
            @"new",
            @"nice",
            @"night",
            @"nine",
            @"nineteen",
            @"ninety",
            @"ninth",
            @"no",
            @"noodle",
            @"noon",
            @"not",
            @"notebook",
            @"November",
            @"now",
            @"number",
            
            
            
            @"October",
            @"octopus",
            @"of",
            @"off",
            @"often",
            @"oh",
            @"OK",
            @"old",
            @"on",
            @"one",
            @"only",
            @"open",
            @"or",
            @"orange",
            @"Orion",
            @"Ottawa",
            @"our",
            @"ours",
            @"over",
            @"own",
            
            
            
            
            
            @"park",
            @"party",
            @"peaceful",
            @"pen",
            @"people",
            @"piano",
            @"picture",
            @"pizza",
            @"plane",
            @"planet",
            @"play",
            @"player",
            @"please",
            @"pocket",
            @"popcorn",
            @"popular",
            @"present",
            
            
            
            
            
            @"question",
            @"quickly",
            @"quiet",
            @"quiz",
            
            
            
            
            
            @"racket",
            @"rain",
            @"read",
            @"ready",
            @"really",
            @"red",
            @"rest",
            @"restaurant",
            @"return",
            @"rice",
            @"ride",
            @"right",
            @"round",
            @"rule",
            @"run",
            @"Russia",
            
            
            
            
            
            @"San Francisco",
            @"Saturday",
            @"school",
            @"season",
            @"seat",
            @"second",
            @"see",
            @"September",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
            @"",
           
          
            
            @"play",
             @"rain",
             @"read",
             @"rest",
             @"ride",
             @"run",
             @"see",
             @"shine",
             @"ski",
             @"speak",
             @"spend",
             @"stand",
             @"start",
             @"stay",
             @"study",
            @"swim",
            @"take",
            @"talk",
            @"teach",
            @"think",
            @"try",
            @"turn",
            @"use",
            @"wait",
            @"walk",
            @"want",
            @"watch",
            @"work",
            @"write",
                 nil];


jobArray =[[NSMutableArray alloc] initWithObjects:
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           @"単語",
           
           nil];



profileArray =[[NSMutableArray alloc] initWithObjects:
              
               @"(意味)〜について",
               @"(意味)〜のあと",
               @"(意味)午後",
               @"(意味)再び",
               @"(意味)〜前に",
               @"(意味)全員",
               
              
               @"(意味)あちこち",
               
            @"(意味)ほとんど",
               @"(意味)〜もまた",
               @"(意味)〜です,〜である,〜にいる",
               @"(意味)アメリカ合衆国",
               @"(意味)〜と〜",
               @"(意味)動物",
               @"(意味)アリ",
               @"(意味)何も無い",
               @"(意味)４月",
               @"(意味)エプロン",
               @"(意味)〜です,〜である,〜にいる",
               @"(意味)場所",
               @"(意味)あたり一面に",
               @"(意味)~として",
               @"(意味)〜で",
               @"(意味)８月",
               @"(意味)オーストラリア",
              
               
              
               @"(意味)戻って",
               @"(意味)かばん",
               @"(意味)ボール",
               @"(意味)バー",
               @"(意味)野球",
               @"(意味)バスケットボール",
               @"(意味)美しい",
               @"(意味)ベッド",
               @"(意味)〜より前",
               @"(意味)〜の後ろの",
               @"(意味)〜の間に",
               @"(意味)大きい",
               @"(意味)自転車",
               @"(意味)鳥",
               @"(意味)誕生日",
               @"(意味)黒い",
               @"(意味)毛布",
               @"(意味)青い",
               @"(意味)ボート",
               @"(意味)本",
               @"(意味)国境",
               @"(意味)ボストン",
               @"(意味)箱",
                @"(意味)男の子",
                @"(意味)朝食",
                @"(意味)橋",
                @"(意味)兄弟",
                @"(意味)バス",
                @"(意味)忙しい",
                @"(意味)しかし",
                @"(意味)〜によって",
                @"(意味)さようなら",
               
               
              @"(意味)ケーブルカー",
               @"(意味)カフェテリア",
               @"(意味)〜に電話をする",
               @"(意味)カメラ",
               @"(意味)キャンプをする",
            @"(意味)〜できる",
               @"(意味)カナダ",
               @"(意味)〜出来ない",
               @"(意味)ぼうし",
               @"(意味)車",
               @"(意味)注意",
               @"(意味)〜のことを気にかける",
               @"(意味)注意して",
               @"(意味)ねこ",
               @"(意味)コンパクトディスク",
               @"(意味)いす",
               @"(意味)おつり",
               @"(意味)お守り",
               @"(意味)声援を送る",
               @"(意味)子供",
               @"(意味)子供たち",
               @"(意味)中国",
               @"(意味)中国人街",
               @"(意味)中国人の",
               @"(意味)都市",
               @"(意味)クラス",
               @"(意味)教室",
               @"(意味)〜を閉める",
               @"(意味)雲",
               @"(意味)曇った",
               @"(意味)寒い",
               @"(意味)色",
               @"(意味)来る",
               @"(意味)クック",
               @"(意味)料理する",
               @"(意味)クッキー",
               @"(意味)国",
               @"(意味)もちろん",
               @"(意味)満員の",
               @"(意味)文化",
               @"(意味)カップ",
              
               @"(意味)日付",
               @"(意味)１日",
               @"(意味)親愛なる",
               @"(意味)１２月",
               @"(意味)机",
               @"(意味)違う",
               @"(意味)難しい",
               @"(意味)夕食",
               @"(意味)〜をする",
               @"(意味)犬",
               @"(意味)ドア",
               @"(意味)〜を通って",
               @"(意味)夢",
               @"(意味)運転する",
               
               
               
               @"(意味)それぞれの",
               @"(意味)早く",
               @"(意味)地球",
               @"(意味)簡単に",
               @"(意味)やさしい",
               @"(意味)〜を食べる",
               @"(意味)卵",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",
               @"(意味)",

               nil];



}


- (void)didReceiveMemoryWarning
{
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

#pragma  mark -テーブルビュー(データソースメソッド)
-(NSInteger)tableView:(UITableView *)tableView
numberOfRowsInSection:(NSInteger)section
{
    return [nameArray count];
}




-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    NSString *cellIdentifier = @"Cell";
    UITableViewCell *cell=[tableView
                           dequeueReusableCellWithIdentifier:cellIdentifier];
    if(!cell) {
        cell =[[UITableViewCell alloc]initWithStyle:
               UITableViewCellStyleDefault reuseIdentifier:
               cellIdentifier];
        
        
        
    }
    
    cell.textLabel.text = [nameArray objectAtIndex:indexPath.row];
    cell.detailTextLabel.text = [jobArray objectAtIndex:indexPath.row];
    return cell;
    
    
    
    
    
    
    
    
    
    
}


-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    NSString*talentName = [nameArray objectAtIndex:indexPath.row];
    NSString*profile=[profileArray objectAtIndex:indexPath.row];
    UIAlertView *alertView = [[UIAlertView alloc]initWithTitle:
                              
                              talentName message:profile delegate:self cancelButtonTitle:@"OK" otherButtonTitles:nil, nil];
    [alertView show];
}













- (BOOL)prefersStatusBarHidden
{
    return YES;
}




@end
